version: '3.7'

services:
  identifier:
    ports:
      - "81:80"
    restart: "no"
  dispatcher:
    restart: "no"
  virtuoso:
    ports:
      - "8894:8890"
    restart: "no"
  resource:
    restart: "no"
  database:
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
      INSPECT_OUTGOING_SPARQL_QUERIES: "true"
      INSPECT_INCOMING_SPARQL_QUERIES: "true"
      LOG_SERVER_CONFIGURATION: "true"
      INSPECT_ACCESS_RIGHTS_PROCESSING : "true"
      LOG_DELTA_MESSAGES : "true"
      LOG_DELTA_CLIENT_COMMUNICATION : "true"
      LOG_TEMPLATE_MATCHER_PERFORMANCE : "true"
      LOG_OUTGOING_SPARQL_QUERY_RESPONSES : "true"
      INSPECT_OUTGOING_SPARQL_QUERY_RESPONSES : "true"
      LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP : "true"
    restart: "no"
  cache:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:0.4.0
    restart: "no"
  migrations:
    restart: "no"
  file:
    restart: "no"
  search-query-management:
    restart: "no"
  enrich-submission:
    restart: "no"
  submissions-consumer:
    restart: "no"
  submissions-dispatcher:
    restart: "no"
  update-bestuurseenheid-mock-login:
    restart: "no"
  reasoner:
    restart: "no"
  op-public-consumer:
    restart: "no"
  worship-submissions-email-notification-service:
    restart: "no"
  deliver-email-service:
    restart: "no"
  vendor-management-consumer:
    restart: "no"
  vendor-login:
    restart: "no"
  sparql-authorization-wrapper:
    restart: "no"