PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

INSERT {
    GRAPH ?g {
        ?s skos:topConceptOf <http://lblod.data.gift/concept-schemes/2f12f269-5024-4cb2-8ca4-f18d21d5fa39>.
        ?s skos:inScheme <http://lblod.data.gift/concept-schemes/2f12f269-5024-4cb2-8ca4-f18d21d5fa39>.
    }
} WHERE {
    GRAPH ?h {
        ?s a besluit:Bestuurseenheid .
    }
    BIND(?h as ?g)
}
