PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
  GRAPH ?g {
    ?email <http://redpencil.data.gift/vocabularies/tasks/numberOfRetries> ?retryCount .
  }
}
INSERT {
  GRAPH ?g {
    ?email <http://redpencil.data.gift/vocabularies/tasks/numberOfRetries> "0"^^xsd:integer .
  }
}
WHERE {
  GRAPH ?g {
    ?email a nmo:Email ;
      nmo:isPartOf <http://data.lblod.info/id/mail-folders/4> ;
      <http://redpencil.data.gift/vocabularies/tasks/numberOfRetries> ?retryCount .
  }
}

